name: 'C++ CI'

on:
  push

jobs:
  build: 
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Init
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build . 

      - name: Upload artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: lab-${{ runner.os }}
          path: Debug/helloworld_cli.exe

      - name: Upload artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: lab-${{ runner.os }}
          path: helloworld_cli
            
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4    
        with:
          path: artifact

      - run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/lab-Linux/helloworld_cli.deb
            artifact/lab-Windows/helloworld_cli.exe
          tag_name: 1.0.${{ github.run_number }}
          body: "Release 1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
